default:
  image: rust:latest

stages:
  - test
  - build-x86_64

test:
  stage: test
  script:
    - cargo build --release
    - cargo test --release
  artifacts:
    paths:
      - target/release/markovify-rs

buid:
  stage: build-x86_64
  image: messense/rust-musl-cross:x86_64-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/markovify-rs
  script:
    - cargo build -r --target x86_64-unknown-linux-musl
