
default:
  image: rust:latest

stages:
  - build
  - test

build:x86_64:
  stage: build
  script:
    - apt update
    - apt install gcc-x86-64-linux-gnu -y
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --release --target x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/markovify-rs
  allow_failure: true

build:arm64:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/markovify-rs

test:arm64:
  stage: test
  script:
    - cargo test --release
  dependencies:
    - build:arm64