
default:
  image: rust:latest

stages:
  - build
  - test

before_script:
  - cargo build --release

build:
  stage: build
  artifacts:
    paths:
      - target/release/markovify-rs

test:
  stage: test
  script:
    - cargo test --release
