
default:
  image: rust:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo build --release
  artifacts:
    paths:
      - target/release/markovify-rs
      
test:
  stage: test
  script:
    - cargo test --release
