
default:
  image: rust:latest

stages:
  - test

test:arm64:
  stage: test
  script:
    - cargo build --release
    - cargo test --release
  dependencies:
    - build:arm64
  artifacts:
    paths:
      - target/release/markovify-rs