name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.arch }}

      - name: Build
        run: cargo build --release --target ${{ matrix.arch }}

      - name: Upload Build Artifacts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release
